### ISSUE TITLE
custom.scss doesn't appear to be affecting published site

### ISSUE THREAD

**Issue by Aariq** [Aariq/website-quarto#34]
Tried manually publishing as well as through GH action and the tweaks made in custom.scss don't take effect

**Comment by Aariq** [comment]
Fixed.  Needed to supply custom.scss to a different spot in the _quarto.yml.  Possibly a bug in Quarto.

``` yaml
format:
  html:
    theme: 
      light: 
        - flatly
        - custom.scss # This works
      dark: 
        - darkly
        - custom.scss # This works
    # css: custom.scss # This works in preview, but not when published
    toc: true


```
