### ISSUE TITLE
Make logo in navbar bigger

### ISSUE THREAD

**Issue by Aariq** [Aariq/website-quarto#6]
I like the way it looks on the current site.

**Comment by Aariq** [comment]
Maybe some answers here: https://stackoverflow.com/questions/40436285/bootstrap-navbar-logo-size

**Comment by Aariq** [comment]
Changing this css seems to work in the browser inspector, but not in custom.scss.  Maybe I'm getting the selectors wrong?

``` scss
// Make logo larger
.navbar-logo {
  max-height: 40px;
}
.navbar-brand {
  padding-top: 0;
  padding-bottom: 0;
}
```
